version: '3.7'

services:
  web:
    build: ./app
    command: gunicorn django_app.wsgi -b 0.0.0.0:8000
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=sp325328uLznTM6QiVSXy52Nwc9C93WrIQAEj9rzeWAAabOJ2E
      - DEBUG=0
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"