# Dockerfile

# Python version
FROM python:3.7-alpine

# Set work directory
WORKDIR /code

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

# Install dependencies
RUN pip install --upgrade pip
COPY requirements.txt /code/requirements.txt
RUN pip install -r requirements.txt

VOLUME /reports_volume

# Copy project
COPY . /code/

# Run entrypoint.sh
ENTRYPOINT ["/code/entrypoint.sh"]