# Generated by Django 3.0.3 on 2020-02-19 21:58

from rest_framework import serializers

from clients.models import (ActionItem, Advisor, Children, Client, Debt,
                            Expense, Goal, Partner, Plan)


class AdvisorSerializer(serializers.ModelSerializer):
    class Meta:
        model = Advisor
        fields = '__all__'


class ClientSerializer(serializers.ModelSerializer):
    class Meta:
        model = Client
        fields = '__all__'


class ExpenseSerializer(serializers.ModelSerializer):
    class Meta:
        model = Expense
        exclude = ['client']


class ChildrenSerializer(serializers.ModelSerializer):
    class Meta:
        model = Children
        exclude = ['client']


class PartnerSerializer(serializers.ModelSerializer):
    class Meta:
        model = Partner
        exclude = ['client']


class GoalSerializer(serializers.ModelSerializer):
    class Meta:
        model = Goal
        exclude = ['client']


class PlanSerializer(serializers.ModelSerializer):
    class Meta:
        model = Plan
        exclude = ['client']


class DebtSerializer(serializers.ModelSerializer):
    class Meta:
        model = Debt
        exclude = ['client']


class ActionItemSerializer(serializers.ModelSerializer):
    class Meta:
        model = ActionItem
        exclude = ['client']
