# Generated by Django 3.0.3 on 2020-02-19 21:58

from django.db import migrations

from rest_framework import serializers
from clients.models import *


class IDSerializer(serializers.Serializer):
    id = serializers.UUIDField(required=True, format='hex_verbose')


class ClientIDSerializer(serializers.Serializer):
    client = serializers.UUIDField(required=True, format='hex_verbose')


class AdvisorSerializer(serializers.ModelSerializer):
    class Meta:
        model = Advisor
        fields = '__all__'


class ClientSerializer(serializers.ModelSerializer):
    class Meta:
        model = Client
        fields = '__all__'


class ExpenseSerializer(serializers.ModelSerializer):
    class Meta:
        model = Expense
        fields = '__all__'


class ChildrenSerializer(serializers.ModelSerializer):
    class Meta:
        model = Children
        fields = '__all__'


class PartnerSerializer(serializers.ModelSerializer):
    class Meta:
        model = Partner
        fields = '__all__'


class GoalSerializer(serializers.ModelSerializer):
    class Meta:
        model = Goal
        fields = '__all__'


class PlanSerializer(serializers.ModelSerializer):
    class Meta:
        model = Plan
        fields = '__all__'