# Generated by Django 3.0.3 on 2020-02-19 21:58

from django.db import migrations

from rest_framework import serializers
from clients.models import Client


class ClientSerializer(serializers.ModelSerializer):
    class Meta:
        model = Client
        fields = ['pk', 'first_name', 'last_name', 'dob', 'email', 'zipcode', 'gross_income',
                  'additional_income', 'job_title']
