# Generated by Django 2.2.10 on 2020-04-13 03:59

import datetime
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(
                    max_length=240, verbose_name='First Name')),
                ('last_name', models.CharField(
                    max_length=240, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(
                    max_length=20, verbose_name='Phone Number')),
                ('address', models.CharField(default='',
                                             max_length=240, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(
                    max_length=240, verbose_name='First Name')),
                ('last_name', models.CharField(
                    max_length=240, verbose_name='Last Name')),
                ('middle_name', models.CharField(default='',
                                                 max_length=240, verbose_name='Middle Name')),
                ('birth_year', models.IntegerField(
                    default=2020, verbose_name='Birth Year')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('city', models.CharField(default='Philadelphia',
                                          max_length=100, verbose_name='City')),
                ('state', models.CharField(default='PA',
                                           max_length=100, verbose_name='State')),
                ('gross_income', models.DecimalField(decimal_places=2,
                                                     default=0.0, max_digits=8, verbose_name='Gross Income')),
                ('after_taxes_income', models.DecimalField(decimal_places=2,
                                                           default=0.0, max_digits=8, verbose_name='After Taxes Income')),
                ('advisor', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.Advisor')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('emergency_savings_factor_upper', models.DecimalField(decimal_places=2,
                                                                       default=0.0, max_digits=8, verbose_name='Emergency Savings Factor Upper')),
                ('emergency_savings_factor_lower', models.DecimalField(decimal_places=2,
                                                                       default=0.0, max_digits=8, verbose_name='Emergency Savings Factor Lower')),
                ('emergency_savings_range_upper', models.DecimalField(decimal_places=2,
                                                                      default=0.0, max_digits=8, verbose_name='Emergency Savings Range Upper')),
                ('emergency_savings_range_lower', models.DecimalField(decimal_places=2,
                                                                      default=0.0, max_digits=8, verbose_name='Emergency Savings Range Lower')),
                ('retirement_factor', models.DecimalField(decimal_places=2,
                                                          default=0.0, max_digits=8, verbose_name='Retirement Factor')),
                ('retirement_value', models.DecimalField(decimal_places=2,
                                                         default=0.0, max_digits=8, verbose_name='Retirement Value')),
                ('budget_savings_factor', models.DecimalField(decimal_places=2,
                                                              default=0.0, max_digits=8, verbose_name='Budget Savings Factor')),
                ('budget_savings_value', models.DecimalField(decimal_places=2,
                                                             default=0.0, max_digits=8, verbose_name='Budget Savings Value')),
                ('budget_fixed_expenses_factor', models.DecimalField(decimal_places=2,
                                                                     default=0.0, max_digits=8, verbose_name='Budget Fixed Expenses Factor')),
                ('budget_fixed_expenses_value', models.DecimalField(decimal_places=2,
                                                                    default=0.0, max_digits=8, verbose_name='Budget Fixed Expenses Value')),
                ('budget_spending_factor', models.DecimalField(decimal_places=2,
                                                               default=0.0, max_digits=8, verbose_name='Budget Spending Factor')),
                ('budget_spending_value', models.DecimalField(decimal_places=2,
                                                              default=0.0, max_digits=8, verbose_name='Budget Spending Value')),
                ('debt_repayment_factor', models.DecimalField(decimal_places=2,
                                                              default=0.0, max_digits=8, verbose_name='Debt Repayment Factor')),
                ('debt_repayment_value', models.DecimalField(decimal_places=2,
                                                             default=0.0, max_digits=8, verbose_name='Debt Repayment Value')),
                ('client', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(
                    max_length=240, verbose_name='First Name')),
                ('last_name', models.CharField(
                    max_length=240, verbose_name='Last Name')),
                ('birth_year', models.IntegerField(
                    default=2020, verbose_name='Birth Year')),
                ('gross_income', models.DecimalField(decimal_places=2,
                                                     default=0.0, max_digits=8, verbose_name='Gross Income')),
                ('additional_income', models.DecimalField(decimal_places=2,
                                                          default=0.0, max_digits=8, verbose_name='Additional Income')),
                ('client', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('goal_type', models.CharField(
                    max_length=240, verbose_name='Goal Type')),
                ('goal_value', models.DecimalField(decimal_places=2,
                                                   default=0.0, max_digits=8, verbose_name='Goal Value')),
                ('goal_end_date', models.DateField(
                    default=datetime.date.today, verbose_name='Goal End Date')),
                ('client', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('bills_housing', models.DecimalField(decimal_places=2,
                                                      default=0.0, max_digits=8, verbose_name='Bills Housing')),
                ('bills_utilities', models.DecimalField(decimal_places=2,
                                                        default=0.0, max_digits=8, verbose_name='Bills Utilities')),
                ('bills_loan_or_debt', models.DecimalField(decimal_places=2,
                                                           default=0.0, max_digits=8, verbose_name='Bills Loan or Debt')),
                ('bills_insurance', models.DecimalField(decimal_places=2,
                                                        default=0.0, max_digits=8, verbose_name='Bills Insurance')),
                ('bills_other', models.DecimalField(decimal_places=2,
                                                    default=0.0, max_digits=8, verbose_name='Bills Other')),
                ('expense_shopping', models.DecimalField(decimal_places=2,
                                                         default=0.0, max_digits=8, verbose_name='Expense Shopping')),
                ('expense_leisure', models.DecimalField(decimal_places=2,
                                                        default=0.0, max_digits=8, verbose_name='Expense Leisure')),
                ('expense_transportation', models.DecimalField(decimal_places=2,
                                                               default=0.0, max_digits=8, verbose_name='Expense Transportation')),
                ('expense_subscriptions', models.DecimalField(decimal_places=2,
                                                              default=0.0, max_digits=8, verbose_name='Expense Subscription')),
                ('client', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(
                    max_length=240, verbose_name='First Name')),
                ('last_name', models.CharField(
                    max_length=240, verbose_name='Last Name')),
                ('birth_year', models.IntegerField(
                    default=2020, verbose_name='Birth Year')),
                ('planning_on_college', models.BooleanField(
                    default=False, verbose_name='Planning On College')),
                ('in_college', models.BooleanField(
                    default=False, verbose_name='In College')),
                ('client', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
