# Generated by Django 2.2.10 on 2020-04-13 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='children',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='advisor',
            new_name='advisor_id',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='client',
            new_name='client_id',
        ),
    ]
