# Generated by Django 2.2.10 on 2020-04-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='retirement_value',
        ),
        migrations.AddField(
            model_name='plan',
            name='recommended_retirement_value',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Recommended Retirement Value'),
        ),
        migrations.AlterField(
            model_name='client',
            name='current_year',
            field=models.IntegerField(editable=False, verbose_name='Current Year'),
        ),
    ]
