# Generated by Django 2.2.10 on 2020-05-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20200430_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='debt_repayment_value',
        ),
        migrations.AddField(
            model_name='plan',
            name='recommended_monthly_maximum_debt_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8, verbose_name='Recommended Monthly Maximum Debt Amount'),
        ),
        migrations.AlterField(
            model_name='client',
            name='total_annual_income',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8, verbose_name='Total Annual Income'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='debt_repayment_factor',
            field=models.DecimalField(decimal_places=2, default=0.36, max_digits=8, verbose_name='Debt Repayment Factor'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='household_annual_net_income',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8, verbose_name='Household Annual Net Income'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='recommended_retirement_value',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8, verbose_name='Recommended Retirement Value'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='retirement_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, editable=False, max_digits=5, verbose_name='Retirement Factor'),
        ),
    ]
