# Generated by Django 2.2.10 on 2020-04-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200413_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='after_taxes_income',
        ),
        migrations.RemoveField(
            model_name='client',
            name='gross_income',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='additional_income',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='gross_income',
        ),
        migrations.AddField(
            model_name='client',
            name='additional_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Additional Income'),
        ),
        migrations.AddField(
            model_name='client',
            name='personal_annual_net_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Personal Annual Net Income'),
        ),
        migrations.AddField(
            model_name='partner',
            name='personal_annual_net_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Personal Annual Net Income'),
        ),
        migrations.AddField(
            model_name='plan',
            name='household_annual_net_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Household Annual Net Income'),
        ),
    ]
