# Generated by Django 2.2.10 on 2020-05-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200503_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='household_annual_net_income',
        ),
        migrations.AddField(
            model_name='client',
            name='household_annual_net_income',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8, verbose_name='Household Annual Net Income'),
        ),
    ]
