# Generated by Django 3.0.3 on 2020-03-07 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20200304_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.Advisor'),
        ),
    ]
