# Generated by Django 2.2.10 on 2020-04-15 05:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20200413_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debt_monthly_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Debt Monthly Amount')),
                ('debt_remaining_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Debt Remaining Total')),
                ('debt_interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Goal Value')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
