# Generated by Django 2.2.10 on 2020-04-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20200415_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.AddField(
            model_name='expense',
            name='bills_housing',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Bills Housing'),
        ),
        migrations.AddField(
            model_name='expense',
            name='bills_insurance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Bills Insurance'),
        ),
        migrations.AddField(
            model_name='expense',
            name='bills_loan_or_debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Bills Loan or Debt'),
        ),
        migrations.AddField(
            model_name='expense',
            name='bills_other',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Bills Other'),
        ),
        migrations.AddField(
            model_name='expense',
            name='bills_utilities',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Bills Utilities'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_leisure',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Expense Leisure'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_shopping',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Expense Shopping'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_subscriptions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Expense Subscription'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_transportation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Expense Transportation'),
        ),
    ]
