# Generated by Django 2.2.10 on 2020-04-15 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20200415_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
    ]
