# Generated by Django 2.2.10 on 2020-04-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20200415_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='bills_loan_or_debt',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='bills_other',
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_other',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Expense Other'),
        ),
    ]
