# Generated by Django 2.2.10 on 2020-04-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20200415_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='housing_type',
            field=models.CharField(choices=[(
                'Rent', 'Rent'), ('Mortgage', 'Mortgage')], default='Rent', max_length=10),
        ),
    ]
