# Generated by Django 2.2.10 on 2020-04-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_expense_housing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='last_name',
        ),
    ]
