# Generated by Django 2.2.10 on 2020-04-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20200421_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='protection_factor_lower',
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=8, verbose_name='Protection Factor Lower'),
        ),
        migrations.AddField(
            model_name='plan',
            name='protection_factor_upper',
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=8, verbose_name='Protection Factor Upper'),
        ),
        migrations.AddField(
            model_name='plan',
            name='protection_range_lower',
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=8, verbose_name='Protection Range Lower'),
        ),
        migrations.AddField(
            model_name='plan',
            name='protection_range_upper',
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=8, verbose_name='Protection Range Upper'),
        ),
    ]
