# Generated by Django 2.2.10 on 2020-04-21 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_actionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='client',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
            preserve_default=False,
        ),
    ]
