# Generated by Django 2.2.10 on 2020-04-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_actionitem_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='combined',
            field=models.CharField(default='', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='plan',
            name='full_name',
            field=models.CharField(default='', editable=False, max_length=256),
        ),
    ]
