# Generated by Django 2.2.10 on 2020-04-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_auto_20200425_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='combined',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='full_name',
        ),
    ]
