# Generated by Django 2.2.10 on 2020-04-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_auto_20200427_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='retirement_value',
        ),
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='current_year',
            field=models.IntegerField(default=2020, editable=False),
            preserve_default=False,
        ),
    ]
