# Generated by Django 3.0.3 on 2020-02-24 16:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=240, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=240, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.PositiveIntegerField(verbose_name='Phone Number')),
                ('address', models.CharField(max_length=240, verbose_name='Address')),
                ('city', models.CharField(max_length=240, verbose_name='City')),
                ('zipcode', models.PositiveIntegerField(verbose_name='Zip code')),
                ('state', models.CharField(max_length=240, verbose_name='State')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=240, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=240, verbose_name='Last Name')),
                ('dob', models.DateField(default=datetime.date.today, verbose_name='DOB')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('zipcode', models.PositiveIntegerField(verbose_name='Zip code')),
                ('job_title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('gross_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Gross Income')),
                ('additional_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Additional Income')),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Advisor')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_savings_factor_upper', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Emergency Savings Factor Upper')),
                ('emergency_savings_factor_lower', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Emergency Savings Factor Lower')),
                ('emergency_savings_range_upper', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Emergency Savings Range Upper')),
                ('emergency_savings_range_lower', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Emergency Savings Range Lower')),
                ('retirement_factor', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Retirement Factor')),
                ('retirement_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Retirement Value')),
                ('budget_savings_factor', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Budget Savings Factor')),
                ('budget_savings_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Budget Savings Value')),
                ('budget_fixed_expenses_factor', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Budget Fixed Expenses Factor')),
                ('budget_fixed_expenses_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Budget Fixed Expenses Value')),
                ('budget_spending_factor', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Budget Spending Factor')),
                ('budget_spending_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Budget Spending Value')),
                ('debt_repayment_factor', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Debt Repayment Factor')),
                ('debt_repayment_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Debt Repayment Value')),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=240, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=240, verbose_name='Last Name')),
                ('dob', models.DateField(default=datetime.date.today, verbose_name='DOB')),
                ('job_title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('gross_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Gross Income')),
                ('additional_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Additional Income')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(max_length=240, verbose_name='Goal Type')),
                ('goal_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Goal Value')),
                ('goal_end_date', models.DateField(default=datetime.date.today, verbose_name='Goal End Data')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bills_housing', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Bills Housing')),
                ('bills_utilities', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Bills Utilities')),
                ('bills_loan_or_debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Bills Loan or Debt')),
                ('bills_insurance', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Bills Insurance')),
                ('bills_other', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Bills Other')),
                ('expense_shopping', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Expense Shopping')),
                ('expense_leisure', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Expense Leisure')),
                ('expense_transportation', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Expense Transportation')),
                ('expense_subscriptions', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Expense Subscription')),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=240, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=240, verbose_name='Last Name')),
                ('dob', models.DateField(default=datetime.date.today, verbose_name='DOB')),
                ('planning_on_college', models.BooleanField(default=False, verbose_name='Planning On College')),
                ('in_college', models.BooleanField(default=False, verbose_name='In College')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
