# Generated by Django 3.0.3 on 2020-03-02 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20200224_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='zipcode',
            field=models.CharField(max_length=10, verbose_name='Zip code'),
        ),
        migrations.AlterField(
            model_name='client',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='clients.Advisor'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zipcode',
            field=models.CharField(max_length=10, verbose_name='Zip code'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
    ]
