# Generated by Django 3.0.3 on 2020-03-04 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200302_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='state',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='job_title',
        ),
    ]
