# Generated by Django 2.2.10 on 2020-05-05 15:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=240, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=240, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('address', models.CharField(default='', max_length=240, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=240, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=240, verbose_name='Last Name')),
                ('middle_name', models.CharField(default='', max_length=240, verbose_name='Middle Name')),
                ('birth_year', models.IntegerField(default=2020, verbose_name='Birth Year')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('city', models.CharField(default='Philadelphia', max_length=100, verbose_name='City')),
                ('state', models.CharField(default='PA', max_length=100, verbose_name='State')),
                ('personal_annual_net_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=8,
                                                                   verbose_name='Personal Annual Net Income')),
                ('additional_income',
                 models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Additional Income')),
                ('current_year', models.IntegerField(editable=False, verbose_name='Current Year')),
                ('age', models.IntegerField(default=0, editable=False, verbose_name='Age')),
                ('total_annual_income', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8,
                                                            verbose_name='Total Annual Income')),
                ('household_annual_net_income',
                 models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8,
                                     verbose_name='Household Annual Net Income')),
                ('advisor',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toastapi.Advisor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protection_factor_upper', models.DecimalField(decimal_places=2, default=0.0, max_digits=8,
                                                                verbose_name='Protection Factor Upper')),
                ('protection_factor_lower', models.DecimalField(decimal_places=2, default=0.0, max_digits=8,
                                                                verbose_name='Protection Factor Lower')),
                ('protection_range_upper', models.DecimalField(decimal_places=2, default=0.0, max_digits=8,
                                                               verbose_name='Protection Range Upper')),
                ('protection_range_lower', models.DecimalField(decimal_places=2, default=0.0, max_digits=8,
                                                               verbose_name='Protection Range Lower')),
                ('emergency_savings_factor_upper', models.DecimalField(decimal_places=2, default=0.0, max_digits=8,
                                                                       verbose_name='Emergency Savings Factor Upper')),
                ('emergency_savings_factor_lower', models.DecimalField(decimal_places=2, default=0.0, max_digits=8,
                                                                       verbose_name='Emergency Savings Factor Lower')),
                ('emergency_savings_range_upper', models.DecimalField(decimal_places=2, default=0.0, max_digits=8,
                                                                      verbose_name='Emergency Savings Range Upper')),
                ('emergency_savings_range_lower', models.DecimalField(decimal_places=2, default=0.0, max_digits=8,
                                                                      verbose_name='Emergency Savings Range Lower')),
                ('budget_savings_factor', models.DecimalField(decimal_places=2, default=0.0, max_digits=8,
                                                              verbose_name='Budget Savings Factor')),
                ('budget_savings_value',
                 models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Budget Savings Value')),
                ('budget_fixed_expenses_factor', models.DecimalField(decimal_places=2, default=0.0, max_digits=8,
                                                                     verbose_name='Budget Fixed Expenses Factor')),
                ('budget_fixed_expenses_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=8,
                                                                    verbose_name='Budget Fixed Expenses Value')),
                ('budget_spending_factor', models.DecimalField(decimal_places=2, default=0.0, max_digits=8,
                                                               verbose_name='Budget Spending Factor')),
                ('budget_spending_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=8,
                                                              verbose_name='Budget Spending Value')),
                ('debt_repayment_factor', models.DecimalField(decimal_places=2, default=0.36, max_digits=8,
                                                              verbose_name='Debt Repayment Factor')),
                ('retirement_factor', models.DecimalField(decimal_places=2, default=1.0, editable=False, max_digits=5,
                                                          verbose_name='Retirement Factor')),
                ('recommended_retirement_value',
                 models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8,
                                     verbose_name='Recommended Retirement Value')),
                ('recommended_monthly_maximum_debt_amount',
                 models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8,
                                     verbose_name='Recommended Monthly Maximum Debt Amount')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='toastapi.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=240, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=240, verbose_name='Last Name')),
                ('birth_year', models.IntegerField(default=2020, verbose_name='Birth Year')),
                ('personal_annual_net_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=8,
                                                                   verbose_name='Personal Annual Net Income')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toastapi.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal_type', models.CharField(max_length=240, verbose_name='Goal Type')),
                ('goal_value',
                 models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Goal Value')),
                ('goal_end_date', models.DateField(default=datetime.date.today, verbose_name='Goal End Date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toastapi.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('housing_type',
                 models.CharField(choices=[('Rent', 'Rent'), ('Mortgage', 'Mortgage')], default='Rent', max_length=10)),
                ('bills_housing',
                 models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Bills Housing')),
                ('bills_utilities',
                 models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Bills Utilities')),
                ('expense_shopping',
                 models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Expense Shopping')),
                ('expense_leisure',
                 models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Expense Leisure')),
                ('expense_transportation', models.DecimalField(decimal_places=2, default=0.0, max_digits=8,
                                                               verbose_name='Expense Transportation')),
                ('expense_subscriptions',
                 models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Expense Subscription')),
                ('expense_other',
                 models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Expense Other')),
                ('current_monthly_protection_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=8,
                                                                           verbose_name='Current Monthly Protection Payment')),
                ('current_protection_coverage', models.DecimalField(decimal_places=2, default=0.0, max_digits=8,
                                                                    verbose_name='Current Protection Coverage')),
                ('current_retirement_savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=8,
                                                                   verbose_name='Current Retirement Savings')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='toastapi.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debt_monthly_amount',
                 models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Debt Monthly Amount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toastapi.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=240, verbose_name='First Name')),
                ('birth_year', models.IntegerField(default=2020, verbose_name='Birth Year')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toastapi.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=240, verbose_name='Description')),
                ('completed', models.BooleanField(verbose_name='Completed')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toastapi.Client')),
            ],
        ),
    ]
