# Generated by Django 2.2.10 on 2020-05-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toastapi', '0002_auto_20200514_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='additional_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Additional Income'),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_annual_net_income',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20, verbose_name='Household Annual Net Income'),
        ),
        migrations.AlterField(
            model_name='client',
            name='personal_annual_net_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Personal Annual Net Income'),
        ),
        migrations.AlterField(
            model_name='client',
            name='total_annual_income',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20, verbose_name='Total Annual Income'),
        ),
        migrations.AlterField(
            model_name='client',
            name='total_monthly_debt_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20, verbose_name='Total Monthly Debt Repayment'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='debt_monthly_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Debt Monthly Amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='bills_housing',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Bills Housing'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='bills_utilities',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Bills Utilities'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='current_monthly_protection_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Current Monthly Protection Payment'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='current_protection_coverage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Current Protection Coverage'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='current_retirement_savings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Current Retirement Savings'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_leisure',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Expense Leisure'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_other',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Expense Other'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_shopping',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Expense Shopping'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_subscriptions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Expense Subscription'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_transportation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Expense Transportation'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='housing_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Mortgage', 'Mortgage')], default='Rent', max_length=15),
        ),
        migrations.AlterField(
            model_name='partner',
            name='personal_annual_net_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Personal Annual Net Income'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='budget_fixed_expenses_factor',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=15, verbose_name='Budget Fixed Expenses Factor'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='budget_savings_factor',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=15, verbose_name='Budget Savings Factor'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='budget_spending_factor',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=15, verbose_name='Budget Spending Factor'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='debt_repayment_factor',
            field=models.DecimalField(decimal_places=2, default=0.36, max_digits=15, verbose_name='Debt Repayment Factor'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='emergency_savings_factor_lower',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=15, verbose_name='Emergency Savings Factor Lower'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='emergency_savings_factor_upper',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=15, verbose_name='Emergency Savings Factor Upper'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='protection_factor',
            field=models.DecimalField(decimal_places=2, default=20.0, editable=False, max_digits=15, verbose_name='Protection Factor'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='recommended_budget_fixed_expenses_value',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20, verbose_name='Recommended Budget Fixed Expenses Value'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='recommended_budget_savings_value',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20, verbose_name='Recommended Budget Savings Value'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='recommended_budget_spending_value',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20, verbose_name='Recommended Budget Spending Value'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='recommended_emergency_savings_range_lower',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20, verbose_name='Recommended Emergency Savings Range Lower'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='recommended_emergency_savings_range_upper',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20, verbose_name='Recommended Emergency Savings Range Upper'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='recommended_monthly_maximum_debt_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20, verbose_name='Recommended Monthly Maximum Debt Amount'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='recommended_protection_value',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20, verbose_name='Recommended Protection Value'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='recommended_retirement_value',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20, verbose_name='Recommended Retirement Value'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='retirement_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, editable=False, max_digits=15, verbose_name='Retirement Factor'),
        ),
    ]
